// Timing and animation config
export const ANIMATION = {
  TYPING_SPEED_FAST: 30,
  TYPING_SPEED_NORMAL: 50,
  TYPING_SPEED_SLOW: 14,
  TYPING_PAUSE_AFTER_COMPLETE: 1500,
  STAGGER_DELAY_BASE: 100,
  STAGGER_DELAY_FAST: 80,
  STAGGER_DELAY_FILTER: 50,
  FADE_IN_STAGGER: 100,
  SMOOTH_REVEAL_DELAY: 300,
  COUNTER_UPDATE_INTERVAL: 20,
  COUNTER_TRIGGER_DELAY: 200,
  COUNTER_INCREMENT_DIVISOR: 100,
  LOADING_SCREEN_HIDE_DELAY: 500,
  TIMELINE_MARKER_ALIGNMENT_DELAY: 350,
  TIMELINE_MARKER_RESIZE_DEBOUNCE: 120,
  MOUSEMOVE_THROTTLE: 16,
  SHINE_REMOVE_DELAY: 600,
  RIPPLE_REMOVE_DELAY: 600,
  CARD_HOVER_TRANSITION: 600,
  DOT_ANIMATION_DELAY: 100,
  NOTIFICATION_SHOW_DELAY: 100,
  NOTIFICATION_HIDE_DELAY: 3000,
  NOTIFICATION_REMOVE_DELAY: 300,
  RESUME_HASH_DELAY: 500,
  FILTER_HIDE_DELAY: 300,
  PROJECT_LOAD_DELAY: 800,
};

export const INTERSECTION_OBSERVER = {
  THRESHOLD_DEFAULT: 0.15,
  THRESHOLD_HEADER: 0.2,
  THRESHOLD_LAZY_LOAD: 0,
  ROOT_MARGIN_DEFAULT: '0px 0px -100px 0px',
  ROOT_MARGIN_HEADER: '0px 0px -50px 0px',
  ROOT_MARGIN_CARDS: '0px 0px -80px 0px',
  ROOT_MARGIN_LAZY_LOAD: '50px',
};

export const SCROLL = {
  NAVBAR_SCROLL_THRESHOLD: 100,
  SMOOTH_SCROLL_OFFSET: 80,
  SCROLL_INDICATOR_HIDE_THRESHOLD: 10,
  SECTION_SCROLL_OFFSET: 150,
};

export const TRANSFORM_3D = {
  ROTATION_MULTIPLIER: 12,
  ROTATION_MULTIPLIER_NEGATIVE: -12,
  TRANSLATE_Z: 60,
};

export const BREAKPOINTS = {
  MOBILE_MAX: 768,
  TABLET_MAX: 1024,
  DESKTOP_MIN: 1025,
};

export const PROJECT_CARD = {
  WIDTH: 420,
  HEIGHT: 750,
};

export const STAGGER = {
  SKILL_CATEGORY_DELAY: 0.1,
  CARD_DELAY: 0.08,
};
